spring: 
  datasource:
   url: jdbc:mariadb://172.30.254.227:3306/db_springboot_backend?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   username: pruebas 
   password: 790821Jason
   driver-class-name: org.mariadb.jdbc.Driver
  jpa: 
     database-platform: org.hibernate.dialect.MySQL57Dialect
     hibernate: 
       ddl-auto: create-drop 
  main: 
    allow-bean-definition-overriding: true
      
logging: 
  level:
   org: 
    hibernate: 
     SQL: debug
     
     
keycloak: 
  auth-server-url: https://keycloak-keycloak.apps.us-west-1.starter.openshift-online.com/auth
  realm: testing
  resource: apisDevelop
  bearer-only: true
  
 