server:
  port: 9876
spring: 
  datasource:
   url: jdbc:mariadb://localhost:3306/db_springboot_backend?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   username: pruebas 
   password: 790821Jason
   driver-class-name: org.mariadb.jdbc.Driver
  jpa: 
     database-platform: org.hibernate.dialect.MySQL57Dialect
     hibernate: 
       ddl-auto: create-drop 
      
logging: 
  level:
   org: 
    hibernate: 
     SQL: debug